import type { Metadata } from "next";
import { ReactNode } from "react";
// 引入 Ant Design 的全局样式
import "antd/dist/reset.css";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js + Ant Design",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="zh-CN">
      <body style={{ margin: 0 }}>{children}</body>
    </html>
  );
}